# Automatic differentiation with torch.autograd

https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html

In [1]:
import torch

In [2]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad = True)
b = torch.randn(3, requires_grad = True)
z = (x @ w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [3]:
print(x)
print(y)
print(z)
print(loss.item())

tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0.])
tensor([ 1.2504, -5.4172,  1.7236], grad_fn=<AddBackward0>)
1.1314939260482788


In [4]:
print(f'Gradient function for z: {z.grad_fn}')
print(f'Gradient function for loss: {loss.grad_fn}')

Gradient function for z: <AddBackward0 object at 0x000002878F6960A0>
Gradient function for loss: <BinaryCrossEntropyWithLogitsBackward0 object at 0x000002878F696370>


In [5]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.2591, 0.0015, 0.2829],
        [0.2591, 0.0015, 0.2829],
        [0.2591, 0.0015, 0.2829],
        [0.2591, 0.0015, 0.2829],
        [0.2591, 0.0015, 0.2829]])
tensor([0.2591, 0.0015, 0.2829])


In [6]:
print(x)

tensor([1., 1., 1., 1., 1.])


In [7]:
print(w)

tensor([[ 1.2779, -0.9638, -0.0776],
        [-1.7955, -0.9772, -0.4282],
        [ 1.1401, -0.9019, -0.1165],
        [ 0.7958, -0.8305,  2.0714],
        [-0.0479, -0.3786,  0.8562]], requires_grad=True)


In [8]:
z = (x @ w) + b
print(z.requires_grad)

True


In [9]:
with torch.no_grad():
    z = (x @ w) + b
print(z.requires_grad)

False


In [10]:
z = (x @ w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [11]:
inp = torch.eye(4,5,requires_grad = True)
out = (inp + 1).pow(2).t()
print(inp)
print(out)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], requires_grad=True)
tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)


In [12]:
out.backward(torch.ones_like(out), retain_graph = True)
print(f'First call:\n {inp.grad}')

First call:
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])


In [13]:
out.backward(torch.ones_like(out), retain_graph = True)
print(f'Second call:\n {inp.grad}')

Second call:
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])


In [14]:
inp.grad.zero_()

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
out.backward(torch.ones_like(out), retain_graph = True)
print(f"\nCall after zeroing gradients\n{inp.grad}")


Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
