# Tensors

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [1]:
import torch
import numpy as np

In [2]:
# Initialising a tensor
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data) # Directly from data - type inferred

In [3]:
np_arr = np.array(data)
x_np = torch.from_numpy(np_arr) # From numpy

In [4]:
x_ones = torch.ones_like(x_data) # Retains shape and dtype of x_data
print(x_ones)

x_rand = torch.rand_like(x_data, dtype = torch.float) # override dtype explicitly
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.2087, 0.4124],
        [0.3067, 0.0017]])


In [5]:
shape = (2,3)
rand = torch.rand(shape)
print(rand)
ones = torch.ones(shape)
print(ones)
zeros = torch.zeros(shape)
print(zeros)

tensor([[0.0303, 0.7202, 0.1824],
        [0.8010, 0.9714, 0.9235]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [8]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [9]:
tensor

tensor([[0.3832, 0.1631, 0.6751, 0.8038],
        [0.2834, 0.6497, 0.0622, 0.7325],
        [0.9067, 0.4693, 0.4548, 0.5866]])

In [10]:
tensor.device

device(type='cpu')

In [11]:
tensor = torch.ones(4,4)
print(tensor[0])

tensor([1., 1., 1., 1.])


In [12]:
tensor[:,0]

tensor([1., 1., 1., 1.])

In [13]:
tensor[...,-1]

tensor([1., 1., 1., 1.])

In [14]:
tensor[:,1] = 0 

In [15]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [16]:
torch.cat([tensor, tensor, tensor], axis= 1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [17]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
tensor @ tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [19]:
tensor @ tensor

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])

In [20]:
tensor.matmul(tensor)

tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])

In [21]:
y = torch.rand_like(tensor)
y

tensor([[0.7018, 0.7255, 0.1697, 0.9892],
        [0.6807, 0.2947, 0.9229, 0.6429],
        [0.5679, 0.3342, 0.7900, 0.5581],
        [0.5296, 0.3955, 0.5782, 0.2221]])

In [22]:
torch.matmul(tensor, tensor.T, out = y)
y

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [23]:
tensor * tensor # element wise product

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
tensor*tensor.T

tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [25]:
torch.mul(tensor,tensor.T)

tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [26]:
agg = tensor.sum()
agg

tensor(12.)

In [27]:
agg.item()

12.0

In [28]:
type(agg)

torch.Tensor

In [30]:
type(agg.item())

float

In [32]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [37]:
tensor.t_() # operands with underscore suffix are inplace

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
tensor

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
tensor.add_(6)

tensor([[7., 7., 7., 7.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])

In [40]:
tensor.mul_(tensor)

tensor([[49., 49., 49., 49.],
        [36., 36., 36., 36.],
        [49., 49., 49., 49.],
        [49., 49., 49., 49.]])

In [41]:
tensor

tensor([[49., 49., 49., 49.],
        [36., 36., 36., 36.],
        [49., 49., 49., 49.],
        [49., 49., 49., 49.]])

Inplace operations save some memory but can be problematic when computing derivatives because of an immediate loss of history - discouraged

Tensors on the CPU and numpy arrays can share underlying memory locations - changing one changes the other

In [42]:
t = torch.ones(5)

In [43]:
t

tensor([1., 1., 1., 1., 1.])

In [44]:
n = t.numpy()

In [45]:
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [46]:
t[1] = 2

In [47]:
t

tensor([1., 2., 1., 1., 1.])

In [48]:
n

array([1., 2., 1., 1., 1.], dtype=float32)

Numpy array to tensor:

In [50]:
n = np.ones((5,5))

In [51]:
t = torch.from_numpy(n)
t

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [52]:
np.add(n,2,out=n)
n

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [53]:
t

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]], dtype=torch.float64)